name: 'Get & Cache dependencies'
inputs: 
  cache:
   description: 'Sample Input variable'
   required: false
   default: 'true'
outputs:
   cache-value:
      description: 'Cache used output file' 
      value: ${{steps.install.outputs.cache}}

Description: 'Get Dependencies and Casching'
runs:
   using: 'composite'
   steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Cashing Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        id: install
        run: |
          npm ci
          echo ${{inputs.cache}}
          echo "::set-output name=cache::'${{inputs.cache}}'"
        shell: bash
 